import Head from "next/head";
import DigitalAssets from "../components/DigitalAssets";
import SecurityIssues from "../components/SecurityIssues";
import WhyChooseUs from "../components/WhyChooseUs";
import OurExperts from "../components/OurExperts";
import Industry from "../components/Industry";
import ExpertsCertified from "../components/ExpertsCertified";
import Partners from "../components/Partners";
import AboutUsSection from "../components/AboutUsSection";
import News from "../components/News/news";
import Dashboard from "@/components/dashboard/Dashboard";
import { useTranslations } from "next-intl";

// Images
import vapt from "../assets/images/vapt.svg";
import grc from "../assets/images/grc.svg";
import iam from "../assets/images/iam.svg";
import siem from "../assets/images/siem.svg";
import partners1 from "../assets/images/partners1.svg";
import partners2 from "../assets/images/partners2.svg";
import partners3 from "../assets/images/partners3.svg";
import partners4 from "../assets/images/partners4.svg";
import partners5 from "../assets/images/partners5.svg";
import partners6 from "../assets/images/partners6.svg";
import partners7 from "../assets/images/partners7.svg";
import TalkUsNowSection from "@/components/shared/TalkUsNowSection";
import ContactForm from "@/components/ContactIsForm/ContactForm";

export default function Home() {
  const t = useTranslations("Meta");
  const t1 = useTranslations("HomeDigitalAssets");
  const t4 = useTranslations("IAMServicePartners");
  const HomeWhyChooseUs = useTranslations("HomeWhyChooseUs");
  const TranslationTalkUsNowSection = useTranslations("TranslationTalkUsNowSection");

  const HomeWhyChooseUsData = [
    {
      icon: siem,
      link: "",
      title: HomeWhyChooseUs("card1Title"),
      dec: HomeWhyChooseUs("card1Desc"),
    },
    {
      icon: siem,
      link: "",
      title: HomeWhyChooseUs("card2Title"),
      dec: HomeWhyChooseUs("card2Desc"),
    },
    {
      icon: siem,
      link: "",
      title: HomeWhyChooseUs("card3Title"),
      dec: HomeWhyChooseUs("card3Desc"),
    },
    {
      icon: siem,
      link: "",
      title: HomeWhyChooseUs("card4Title"),
      dec: HomeWhyChooseUs("card4Desc"),
    },
  ];
  const DigitalAssetsServices = [
    {
      icon: iam,
      name: `IAM ${t1("Deployment_Services")}`,
      link: "/services/IAM",
      title: t1("title1"),
      desc: t1("desc1"),
    },
    {
      icon: grc,
      name: `GRC ${t1("Deployment_Services")}`,
      link: "/services/GRC",
      title: t1("title2"),
      desc: t1("desc2"),
    },
    {
      icon: siem,
      name: `SIEM ${t1("Deployment_Services")}`,
      link: "/services/data-protection/SIEM",
      title: t1("title3"),
      desc: t1("desc3"),
    },
    {
      icon: vapt,
      name: `VAPT ${t1("Deployment_Services")}`,
      link: "/services/VAPT",
      title: t1("title4"),
      desc: t1("desc4"),
      },
  ];
  const PartnersList = [
    {
      image: partners1
    },
    {
      image: partners2
    },
    {
      image: partners3
    },
    {
      image: partners4
    },
    {
      image: partners5
    },
    {
      image: partners6
    },
    {
      image: partners7
    },
    {
      image: partners1
    },
    {
      image: partners2
    },
    {
      image: partners3
    },
    {
      image: partners4
    },
    {
      image: partners5
    },
    {
      image: partners6
    },
    {
      image: partners7
    },
    {
      image: partners1
    },
    {
      image: partners2
    },
    {
      image: partners3
    },
    {
      image: partners4
    },
    {
      image: partners5
    },
    {
      image: partners6
    },
    {
      image: partners7
    },
    {
      image: partners1
    },
    {
      image: partners2
    },
    {
      image: partners3
    },
    {
      image: partners4
    },
    {
      image: partners5
    },
    {
      image: partners6
    },
    {
      image: partners7
    },
  ];

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Dashboard />
      <DigitalAssets
        title={t1('heading')}
        data={DigitalAssetsServices}
        Read_More={t1('Read More')}
        center_text={t1('Our Services')}
      />
      <SecurityIssues />
      <WhyChooseUs
        title={HomeWhyChooseUs("Outsource Our Deployment Support Team In Ksa")}
        subtitle={HomeWhyChooseUs("Why Choose Us")}
        data={HomeWhyChooseUsData}
        mode=""
        brandLogo={""}
      />
      <OurExperts />  
      <Industry mode="dark" />
      <TalkUsNowSection
        title={TranslationTalkUsNowSection("title")}
        desc={TranslationTalkUsNowSection("desc")}
        link={"/contact-us"}
        linkText={TranslationTalkUsNowSection("linkText")}
        background={""}
      />
      <ExpertsCertified />
      <Partners
        title={t4('title')}
        desc={t4('desc')}
        data={PartnersList}
        fullWidth={true}
      />
      <AboutUsSection />
      <News />
      <ContactForm Image2 />
    </>
  );
}
